cacounicamp/Manual-do-Bixo

barao/comida.tex
Alguns números não puderam ser confirmados. Neste caso, deixei um TODO, ao invez de apagar completamente, visto fiz as ligações dia 03/01 e muita gente vai emendar o feriado.
=> Verifica e atualiza números da seção "Comidas"

barao/transporte.tex
Foram atualizadas informações sobre as modalidades do Bilhete Único (incluído o Bilhete Único Universitário), sobre a tarifa do transporte público (incluído o aumento de janeiro de 2015) e retiradas reticências que eram exibidas nas listas de itens.
=> Bilhete Único, tarifa e demais correções

barao/comida.tex
Tirei uma frase que dava uma ideia desnecessariamente negativa do RA. Troquei CU por RA. Alguém carrega o CU pra bandejar? Hue. Tirei a observação sobre fechamento de cantinas visto que estão praticamente normalizadas. O Tilli Center e o Subway estavam supervalorizados. O Alabama é uma opção boa e bem barata de marmita, não tenho o telefone, mas seria uma boa adição na parte de entrega de marmitas.
=> atualizando comida

README.md
Coloquei as próximas modificações que devem ser feitas no manual!
=> adding issues

alem_da_graduacao/caco.tex, unicamp/disciplinas.tex
Adicionei o que foi pedido pelo DoFoo. As mudanças foram nas seguintes seções:
- Alteração na descrição daSalinha do CACo.
- Adição do CACo Empresta.
- Na seção de matrícula, foram adicionados alguns comentários sobre alteração.
=> colocando os textos do DoFoo

alem_da_graduacao/caco.tex
=> acertando detalhes

alem_da_graduacao/caco.tex
=> alterando gestão

README.md
Tentando manter as coisas mais organizadas!
=> atualizando lsita de to do's

barao/comida.tex
=> adicionando domino's

alem_da_graduacao/eventos.tex, alem_da_graduacao/grupos_entidades.tex, alem_da_graduacao/servicos.tex, barao/comida.tex, barao/diversao.tex, barao/lugares_para_morar.tex, barao/outras_necessidades.tex, barao/transporte.tex
Mudei todas as coisas que estavam no Issue #94 . Retirei links quebrados, troquei pelos o que estavam lá e editei algumas descrições, como foi o caso das caronas.
=> Adicionando as mudanças de links quebrados do DoFoo

README.md, alem_da_graduacao/caco.tex, barao/comida.tex, unicamp/disciplinas.tex
=> Mudanca de catalogo, atualizando horarios, datas e todo.

barao/outras_necessidades.tex
Resolvendo issue sobre falta do supermercado dia da avenida 2.
=> Adicionando Supermercado Dia

alem_da_graduacao/grupos_entidades.tex
Basicamente resolvendo a issue #92
=> Anos que a Unicamp levou times para a ACM-ICPC (final).

barao/outras_necessidades.tex, unicamp/siglas.tex
Acertos referentes a esse issue: #91
=> Atualizando Representantes discentes

barao/comida.tex
=> Adicionando De La Rua (Tentativa Numero 3)

README.md, barao/transporte.tex, unicamp/disciplinas.tex
=> Adicionando CEL/atualizando dados de transporte

alem_da_graduacao/servicos.tex, unicamp/bem_vindo_a_academia.tex
Contêm algumas anotações de `TODO`s com pontos que seria bom conferir:
Also, eu sou péssimo pra escrever com `*`, normalmente eu tento escrever com palavras sem gênero e no tive muito tempo de ler como estamos escrevendo essas coisas, qualquer ponto será muito bem vindo.
:couple_with_heart_man_man: :couple_with_heart_woman_man: :couple_with_heart_woman_woman: 
Relacionado à Issue #105.
=> Seção sobre monitoria

01-ola_mundo/bem_vind0x2a.tex, 01-ola_mundo/pra_pensar.tex, 02-barao/comida.tex, 02-barao/diversao.tex, 02-barao/lugares_para_morar.tex, 02-barao/outras_necessidades.tex, 02-barao/transporte.tex, 03-unicamp/bem_vindo_a_academia.tex, 03-unicamp/cr_reprovacao.tex, 03-unicamp/disciplinas.tex, 03-unicamp/email.tex, 03-unicamp/lugares_para_estudar.tex, 03-unicamp/pra_que_estou_estudando_isso.tex, 04-alem_da_graduacao/caco.tex, 04-alem_da_graduacao/eventos.tex, 04-alem_da_graduacao/servicos.tex, manual_do_bixo.tex
Prefácio: mudança para substantivos femininos ou neutros
Capítulo 1: Mudança para substantivos femininos ou neutros
Capítulo 2: Mudança para substantivos femininos ou neutros
Capítulo 3: Mudança para substantivos femininos ou neutros
Capítulo 4: Mudança para substantivos femininos ou neutros
Arrumando formatação
=> Mudança para substantivos femininos ou neutros (Closes #143)

03-unicamp/siglas.tex
Atualizei os representantes discentes e coordenadores, porém ainda falta completar alguns emails.
=> Atualizando representante discentes (Closes #141)

manual_do_bixo.tex
Há alguém talvez fazendo a nova arte, se ficar boa, trocamos e adiamos esta. Fiz para garantir que teríamos uma arte.
=> Adicionando arte 2018 (Closes #129)

03-unicamp/siglas.tex
Sonho num dia em que eu compile o código dos outros ou note problemas antes.
=> Corrigindo formatação de e-mails e nomes longos (Closes #141)

01-ola_mundo/bem_vind0x2a.tex, 02-barao/comida.tex, 02-barao/diversao.tex, 02-barao/lugares_para_morar.tex, 02-barao/outras_necessidades.tex, 02-barao/transporte.tex, 03-unicamp/bem_vindo_a_academia.tex, 03-unicamp/cr_reprovacao.tex, 03-unicamp/email.tex, 03-unicamp/lugares_para_estudar.tex, 03-unicamp/melhores_banheiros.tex, 03-unicamp/pra_que_estou_estudando_isso.tex, 03-unicamp/siglas.tex, 04-alem_da_graduacao/aaacec.tex, 04-alem_da_graduacao/caco.tex, 04-alem_da_graduacao/computing4all.tex, 04-alem_da_graduacao/eventos.tex, 04-alem_da_graduacao/grupos_entidades.tex, 04-alem_da_graduacao/servicos.tex, README.md, manual_do_bixo.tex
Além disso, formatando melhor enumerações e lista de itens, corrigindo avisos de compilação (_"paragraph too wide"_, usos de `\it` e `\bf`).
=> Adicionando estatística da pesquisa de custo de vida de Barão Geraldo (Closes #135)

02-barao/comida.tex
Nesse PR vou enviar as modificações que fecham a issue #193. ~Quando tiver completo, vou tirar o [WIP] do título~
Todos os estabelecimentos da issue foram adicionados.
=> Adicionando estabelecimentos novos (Closes #193)

02-barao/comida.tex
Relacionado com a issue #165 e com o PR #190 
Esse PR só remove ou substitui os estabelecimentos fechados. Fiz cada estabelecimento em um commit para caso seja necessário fazer algum cherry-picking pra manter a compatibilidade com o PR #190 
Feliz Natal! :santa: :christmas_tree:
=> Remove estabelecimentos fechados

02-barao/comida.tex
* Substituindo Pepe Loco por Yespeto
* Adicionando Frutilatte, Açaí da Barra e Colorê
Aceito sugestões de novos lugares.
=> Adicionando alguns comércios novos (Closes #165)

02-barao/outras_necessidades.tex
=> Remove posto da FEAGRI e atualiza nome do Posto Futuro

02-barao/comida.tex
A Cantina do DCE foi adicionada, foram feitas ressalvas da cantina da FEA/FEM e da Física estarem fechadas e os textos das demais foram modificadas de forma a detalhar melhor cada uma. Além disso, foi acrescentado mais texto no tópico da feirinha
=> Correção do texto das cantinas e feirinha

03-unicamp/siglas.tex
Apenas descrevendo um exemplo do que pode ser visto na CI (updates do IC4, no caso).
=> Exemplificando a CI

03-unicamp/melhores_banheiros.tex
Tentei fazer algo criativo, falei nao só dos banheiros da pós mas também dos do primeiro andar.
=> Atualizando os banheiros no IC-3.5 (Closes #200)
